#!/bin/bash

file="dns_file.txt"

if [ ! -s $1 ]; then
   echo "Passed file is empty"

else
   while read host
   do
         echo $host
         dig +short $host
         dig +short ns $host
         echo ""
         done < $file
fi
